---
- name: Copy docker compose
  hosts: nfs-clients
  become: true


  tasks:
    - name: copy docker compose
      copy:
        src: '/home/vagrant/artefacts/scripts/docker/'
        dest: '/home/vagrant'
        owner: root
        mode: '0640'
        directory_mode: