---
- name: Install Jenkins
  hosts: jenkins
  gather_facts: false
  become: true
  
  tasks:
          
    - name: get the package
      command: > 
        cd /home/vagrant;  curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee   /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    - name: signed key
      command: > 
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update the package
      command: apt-get update -y && apt-get install -y jenkins
      
    - name: apply new jenkins user
      command: gpasswd -a jenkins docker && newgrp docker

    - name: start jenkins
      command: systemctl start jenkins

    - name: open port
      command: ufw allow 8080
    - name: allow openssh
      command: ufw allow OpenSSH
    - name: allow
      command: ufw enable
  
