---
- name: Installing NFS Client 
  hosts: nfs-clients
  become: true
  
  vars:
    nfsserver: 192.168.99.150
    nfs_mountpoint: /nfs
    nfsexport: /share

  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=present update_cache=yes

    - name: Create mountable dir
      file: path={{ nfs_mountpoint }} state=directory mode=777 owner=root group=root

    - name: set mountpoints
      mount: name={{ nfs_mountpoint }} src={{ nfsserver }}:{{ nfsexport }} fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted
    
    - name: copy /etc/exports
      template: src={{ src_exports }} dest=/etc/exports owner=root group=root
    
    - name: Run ufw allow http script 
      command: ufw allow http

    - name: Run ufw allow https script 
      command: ufw allow https

    - name: Run ufw allow to open port
      command: ufw allow 8888

    - name: Run ufw allow to open port
      command: ufw allow 8761

    - name: Run ufw allow to open port
      command: ufw allow 8081

    - name: Run ufw allow to open port
      command: ufw allow 8888

    - name: Run ufw allow to open port
      command: ufw allow 8082

    - name: Run ufw allow to open port
      command: ufw allow 8083

    - name: Run ufw allow to open port
      command: ufw allow 9411

    - name: Run ufw allow to open port
      command: ufw allow 9090

    - name: Run ufw allow to open port
      command: ufw allow 3000

    - name: Run ufw allow to open port
      command: ufw allow 9091

    - name: Run ufw allow OpenSSH script 
      command: ufw allow OpenSSH
      
    - name: enable  ufw
      command: ufw enable

    - name: GitLab Restart with restart
      command: gitlab-ctl restart

    - name: GitLab gitlab-runsvdir status
      command: service gitlab-runsvdir status 
      
    - name: restart nfs client
      service: name=nfs-kernel-server state=restarted