---
- name: Installing NFS Server 
  hosts: added
  become: true
     
  tasks:
    - name: restart cotainers
      command: >
        sh -c 'cd /home/vagrant/artefacts/scripts/docker/; docker-compose up -d'
        
