---
- name: Installing NFS Server 
  hosts: nfs-server
  become: true
     
  tasks:
    - name: restart cotainers
      command: >
        sh -c 'cd /home/vagrant/; docker-compose up -d'
        
